# Generated by Django 4.2.3 on 2023-07-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_description', models.TextField()),
                ('event_date', models.DateTimeField(verbose_name='event date')),
                ('event_location', models.CharField(max_length=200)),
                ('event_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
