# Generated by Django 4.2.3 on 2023-07-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
