# Generated by Django 4.2.1 on 2023-06-18 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_bloglist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogList',
        ),
    ]
