# Generated by Django 4.2.1 on 2023-06-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0003_delete_bloglist'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likesUserArray',
            field=models.TextField(default='[]'),
        ),
    ]
