# Generated by Django 4.2.1 on 2023-06-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0005_alter_blog_likesuserarray'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='likesUserArray',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
