# Generated by Django 4.2.1 on 2023-06-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0006_alter_blog_likesuserarray'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='userImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
