# Generated by Django 4.1.7 on 2023-03-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.CharField(default='first', max_length=200),
            preserve_default=False,
        ),
    ]
