# Generated by Django 4.1.7 on 2023-03-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_blog_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
