# Generated by Django 4.1.7 on 2023-04-01 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_businessman_galleryimages_businessman_phonenumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessman',
            old_name='galleryImages',
            new_name='galleryImages1',
        ),
        migrations.AddField(
            model_name='businessman',
            name='galleryImages2',
            field=models.ImageField(default='No image', upload_to=''),
        ),
        migrations.AddField(
            model_name='businessman',
            name='galleryImages3',
            field=models.ImageField(default='No image', upload_to=''),
        ),
        migrations.AddField(
            model_name='businessman',
            name='galleryImages4',
            field=models.ImageField(default='No image', upload_to=''),
        ),
        migrations.AddField(
            model_name='businessman',
            name='galleryImages5',
            field=models.ImageField(default='No image', upload_to=''),
        ),
    ]
