# Generated by Django 4.1.7 on 2023-04-01 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_businessman_galleryimages1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessman',
            name='galleryImages1',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='galleryImages2',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='galleryImages3',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='galleryImages4',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='galleryImages5',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
        migrations.AlterField(
            model_name='businessman',
            name='userImage',
            field=models.ImageField(default='No image', upload_to='static/gallery'),
        ),
    ]
