# Generated by Django 4.1.7 on 2023-04-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_businessman_galleryimages1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessman',
            name='address',
            field=models.TextField(default='2257/171', max_length=200),
            preserve_default=False,
        ),
    ]
